version: '3.3'
services:
  mariadb:
    image: yobasystems/alpine-mariadb:arm64v8
    environment:
      MYSQL_DATABASE: 'euro_cup_2016'
      MYSQL_ROOT_PASSWORD: 'change-me'
    ports:
      - '3306:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always

volumes:
  mariadb-data: